import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://force-page-7264-dev-ed.scratch.lightning.force.com/lightning")

    page.get_by_role("button", name="App Launcher").click()
    page.get_by_label("View All Applications").click()
    page.get_by_role("link", name="Alex Console").click()
    page.get_by_role("button", name="Show more actions").click()
    page.get_by_role("menuitem", name="New").click()
    page.get_by_label("*Board Name").click()
    page.get_by_label("*Board Name").fill("Playwright Test Board")
    page.get_by_role("combobox", name="Type").click()
    page.get_by_role("option", name="Project").click()
    page.get_by_role("combobox", name="Type").click()
    page.get_by_role("combobox", name="Status").click()
    page.get_by_role("option", name="Published").click()
    page.get_by_label("Email Notifications").uncheck()
    page.get_by_role("button", name="Save", exact=True).click()
    page.get_by_role("button", name="Split view mode").click()
    page.get_by_role("button", name="Create Column").click()
    page.locator("#input-321").click()
    page.locator("#input-321").fill("Backlog")
    page.locator("#input-321").press("Tab")
    page.locator("#input-326").fill("10")
    page.get_by_label("", exact=True).select_option("ColumnStatus.Backlog")
    page.get_by_label("ColumnHeadersRepeater", exact=True).click()
    page.locator("#input-344").click()
    page.locator("#input-344").fill("To Do")
    page.locator("#input-349").click()
    page.locator("#input-349").fill("20")
    page.get_by_role("group", name="ColumnHeadersRepeater instance 2").get_by_label(
        "", exact=True).select_option("ColumnStatus.To Do")
    page.get_by_label("ColumnHeadersRepeater", exact=True).click()
    page.locator("#input-367").click()
    page.locator("#input-367").fill("Doing")
    page.locator("#input-372").click()
    page.locator("#input-372").fill("30")
    page.get_by_role("group", name="ColumnHeadersRepeater instance 3").get_by_label(
        "", exact=True).select_option("ColumnStatus.In Progress")
    page.get_by_label("ColumnHeadersRepeater", exact=True).click()
    page.locator("#input-390").click()
    page.locator("#input-390").fill("Done")
    page.locator("#input-390").press("Tab")
    page.locator("#input-395").fill("40")
    page.get_by_role("group", name="ColumnHeadersRepeater instance 4").get_by_label(
        "", exact=True).select_option("ColumnStatus.Done")
    page.get_by_role("button", name="Next").click()
    page.get_by_role("button", name="Next").click()
    expect(page.get_by_role("link", name="Backlog")).to_be_visible()
    expect(page.get_by_role("link", name="To Do")).to_be_visible()
    expect(page.get_by_role("link", name="Doing")).to_be_visible()
    expect(page.get_by_role("link", name="Done")).to_be_visible()
    page.get_by_role("button", name="Add New Card Add New Card").first.click()
    expect(page.get_by_role("paragraph").get_by_text("Backlog")).to_be_visible()
    page.get_by_role("button", name="Add New Card Add New Card").nth(1).click()
    expect(page.locator("p").filter(
        has_text="To Do").locator("span")).to_be_visible()
    page.get_by_role("button", name="Add New Card Add New Card").nth(2).click()
    expect(page.get_by_text("In Progress")).to_be_visible()
    page.get_by_role("button", name="Add New Card Add New Card").nth(3).click()
    expect(page.locator("p").filter(
        has_text="Done").locator("span")).to_be_visible()
